{
 "title": "分区/总览",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CPU总量",
   "type": "singlestat",
   "description": "$namespace内CPU总量",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.cpu\"}"
    }
   ]
  },
  {
   "title": "CPU Requests占用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"xuwenbao-test\"}) / scalar(kube_resourcequota{namespace=\"xuwenbao-test\", type=\"hard\", resource=\"limits.cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU Limit占有率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\"}) / scalar(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.cpu\"}) * 100"
    }
   ]
  },
  {
   "title": "内存总量",
   "type": "singlestat",
   "description": "$namespace内Mem总量",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"}"
    }
   ]
  },
  {
   "title": "内存 Requests占用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) / scalar(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"}) * 100"
    }
   ]
  },
  {
   "title": "内存 Limit占用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) / scalar(kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"}) * 100"
    }
   ]
  },
  {
   "title": "可分配CPU总量",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.cpu\"} - ignoring(type) kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.cpu\"}"
    }
   ]
  },
  {
   "title": "可分配内存总量",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_resourcequota{namespace=\"$namespace\", type=\"hard\", resource=\"limits.memory\"} - ignoring(type) kube_resourcequota{namespace=\"$namespace\", type=\"used\", resource=\"limits.memory\"}"
    }
   ]
  },
  {
   "title": "运行中Pod数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=~\"Running\",namespace=~\"$namespace\"}==1)"
    }
   ]
  },
  {
   "title": "Ready Pod数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment期望Pod数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_spec_replicas{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment可用Pod数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Deployment不可用Pod数量",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Ingress吞吐量",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Ingress P99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\", exported_namespace=\"$namespace\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Ingress访问成功率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{exported_namespace=\"$namespace\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Tomcat HTTP线程连接数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tomcat_threadpool_connectioncount{namespace=\"$namespace\", protocol=\"http-nio\"}) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Tomcat HTTP线程数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tomcat_threadpool_currentthreadcount{namespace=\"$namespace\", protocol=\"http-nio\"}) by(app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "TP10 Pod CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(topk(10, sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\"}[5m])) by (container_name,container_cpu_usage_seconds_total))) * 100",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top10 Pod 内存占用",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(topk(10,sum(container_memory_usage_bytes{namespace=\"$namespace\", container_name!=\"\", container_name!=\"POD\"}) by (container_name,container_memory_usage_bytes)))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "$namespace下磁盘io",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_write_time_seconds_total{namespace=~\"$namespace\"})",
     "legendFormat": "node disk write bytes/s"
    },
    {
     "expr": "sum(node_disk_read_time_seconds_total{namespace=~\"$namespace\"})",
     "legendFormat": "node disk read bytes/s"
    }
   ]
  },
  {
   "title": "$namespace内容器总网络传输TX (bytes/sec)",
   "type": "singlestat",
   "description": "$namespace内容器总网络传输TX (bytes/sec)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "$namespace内容器总网络传输RX(bytes/sec)",
   "type": "singlestat",
   "description": "$namespace内容器总网络传输RX (bytes/sec)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\"}[5m]))"
    }
   ]
  }
 ]
}