{
 "title": "Jenkins",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Job数量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_job_count_value" }
   ]
  },
  {
   "title": "构建成功次数（周）",
   "type": "singlestat",
   "description": "计算构建时间在24小时内的变化次数，某些情况下会出现少计算一次的情况，如：\n24小时新创建的Job，第一次构建不会计入其中。",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(jenkins_last_build_timestamp_seconds{result=\"successful\"}[7d]))"
    }
   ]
  },
  {
   "title": "构建失败次数（周）",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(jenkins_last_build_timestamp_seconds{result=\"unsuccessful\"}[7d]))"
    }
   ]
  },
  {
   "title": "启用插件数量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_active" }
   ]
  },
  {
   "title": "禁用插件数量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_inactive" }
   ]
  },
  {
   "title": "可升级插件数量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_withUpdate" }
   ]
  },
  {
   "title": "失效插件数量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "jenkins_plugins_failed" }
   ]
  },
  {
   "title": "构建成功次数（24小时）",
   "type": "singlestat",
   "description": "计算构建时间在24小时内的变化次数，某些情况下会出现少计算一次的情况，如：\n24小时新创建的Job，第一次构建不会计入其中。",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(jenkins_last_build_timestamp_seconds{result=\"successful\"}[24h]))"
    }
   ]
  },
  {
   "title": "构建成功/失败时间分布",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "每个点代表一次构建 （1成功，-1失败）" }
   ],
   "targets": [
    {
     "expr": "(jenkins_last_build_number{result=\"successful\"} - jenkins_last_build_number{result=\"successful\"} offset 1m) > 0",
     "legendFormat": "{{jenkins_job}}"
    },
    {
     "expr": " (jenkins_last_build_number{result=\"unsuccessful\"} offset 1m) - (jenkins_last_build_number{result=\"unsuccessful\"}) < 0",
     "legendFormat": "{{jekins_job}}"
    }
   ]
  },
  {
   "title": "构建失败次数（24小时）",
   "type": "singlestat",
   "description": "计算构建时间在24小时内的变化次数，某些情况下会出现少计算一次的情况，如：\n24小时新创建的Job，第一次构建不会计入其中。",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(jenkins_last_build_timestamp_seconds{result=\"unsuccessful\"}[24h]))"
    }
   ]
  },
  {
   "title": "Top10 Job构建耗时",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sort(topk(10, jenkins_last_build_duration_seconds{result=~\"successful|unsuccessful\"}))"
    }
   ]
  },
  {
   "title": "Top10 构建失败率（周）",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sort(\n  topk(\n    10, \n    sum(changes(jenkins_last_build_timestamp_seconds{result=\"unsuccessful\"}[7d])) by (jenkins_job) / sum(changes(jenkins_last_build_timestamp_seconds{result=~\"successful|unsuccessful\"}[7d])) by (jenkins_job) * 100\n  )\n)"
    }
   ]
  }
 ]
}